### ISSUE TITLE
Translate all static pages to Spanish

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb3#514]
For clarification, babeldown would do the first translation! For each translation, I will also need to manually edit HTML templates to add i18n variables.

Outside of the blog, we don't have that much content so it's not a too big endeavor.

Not to translate

- 404
- events? #510 
- use cases? #511 
- news page? #515

To translate

- [x] `about.md` (actually not Markdown content) #922 
- [x] `archive/_index.md` (already with `es`, `fr` and `en`)
- [x] `champions/_index.md` #924  https://github.com/ropensci/roweb3/pull/937
- [x] `career/_index.md` #910
- [x] `citations/_index.md` #900
- [x] `commcalls/_index.md` #901 
- [x] `community/_index.md` #903
- [x] `contact/_index.md` #911
- [x]  `coworking/_index.md` #913
- [x] `donate/_index.md` #914
- [x] `help-wanted/_index.md` #915
- [x] `how-to-cite-ropensci.md` #917
- [x] `multilingual-publishing/_index.md` #909
- [x] `packages/_index.md` + other Markdown files. #918
- [x] `papers/_index.md` #919
- [x] `resources/_index.md` #920
- [x] `r-universe/_index.md` #898
- [x] `software-review/_index.md` #916
- [x] `talks/_index.md` #921 
- [x] `talks-papers/_index.md` #921  
- [x] `training/_index.md` #921 
- [x] `tutorials/_index.md` #921

**Comment by yabellini** [comment]
Yes, I will do the review. :-)

**Comment by maelle** [comment]
@yabellini reminder that we have this issue. If it is not useful, we can close it.

**Comment by yabellini** [comment]
It is useful! I will be checking the pages when I get to them.

**Comment by yabellini** [comment]
I think we can close this one, right? @maelle What do you think?

**Comment by yabellini** [comment]
Multilingüal Home Page merged, I will close this one.  Nice job 😄
